Consider the below code to answer further questions:


In [12]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

ans: 

The List refers to a collection of various elements in a sequence, in which every element is basically an object. Also, we can access these elements by their positions (index). On the other hand, an ArrayList creates an array (dynamic) of the objects that can easily reduce or increase in size as and when required.
    

Lists and arrays both are mutable and store ordered items. List can store elements of different types, but arrays can store elements only of the same type. List provides more flexibility as it doesn't require explicit looping, but arrays require explicit looping to print elements.

In [13]:
print(list_)

['1', '2', '3', '4', '5']


In [14]:
print(array_list)

['1' '2' '3' '4' '5']


In [15]:
arr_2d = [[1,2],[3,4]]

In [16]:
print(arr_2d)

[[1, 2], [3, 4]]


In [17]:
array_list.dtype

dtype('<U1')

In [18]:
type(list_)

list

Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [19]:
variable_list = ["sudh", 234, True,5.65]

In [52]:
variable_list

['sudh', 234, True, 5.65]

In [27]:
array_list1 = np.array([[1,2],[2,3]])

In [54]:
array_list1

array([[1, 2],
       [2, 3]])

In [28]:
for i in variable_list:
    print(type(i))

<class 'str'>
<class 'int'>
<class 'bool'>
<class 'float'>


In [55]:
for i in array_list1:
    for j in i:
        print(i.dtype)

int64
int64
int64
int64


Q3. Considering the following changes in the variable, array_list:
    
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [26]:
array_list = np.array(object = list_, dtype = int)

In [51]:
array_list

array([1, 2, 3, 4, 5])

yes, there will be difference in the datatype of the elements present in both the variable list_ and array_list.

datatype of array_list will be int64.

Int64 is an immutable value type that represents signed integers with values that range from negative 9,223,372,036,854,775,808 (which is represented by the Int64. MinValue constant) through positive 9,223,372,036,854,775,807 (which is represented by the Int64. MaxValue constant.

datatype of list_ will be list.

The LIST data type is a collection type that can store ordered non-NULL elements. Lists are used to store multiple items in a single variable.

In [30]:
print(array_list.dtype)

int64


In [31]:
print(type(list_))

<class 'list'>


Consider the below code to answer further questions:


In [32]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [50]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
num_array.ndim

2

In [35]:
num_array.size

6

In [36]:
num_array.shape

(2, 3)

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [39]:
arr = np.zeros((3,3))

In [46]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
arr.shape

(3, 3)

In [41]:
arr.size

9

Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [44]:
arr1 = np.eye(5)

In [45]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [48]:
arr1.shape

(5, 5)

In [49]:
arr1.size

25